### ISSUE TITLE
Maya 2019.3 Error

### ISSUE THREAD

**Issue by ban3bbal000** [revoconner/metahuman_rig_transfer#1]
Hi,

I tried to use the script but I always got this error: 

cmds.confirmDialog( title='Reset Done', message='Proceed now', button=['Yes'], defaultButton='Yes', dismissString='No')

# Error: IOError: file <maya console> line 42: 42 #

If you have any solution for this I would appreciate it greatly.

**Comment by revoconner** [comment]
Check to see if all the scripts are in the same path and you are not using any quotes anything when pasting the path.
