### ISSUE TITLE
calculating offset is not accurate 

### ISSUE THREAD

**Issue by miccall** [revoconner/metahuman_rig_transfer#4]
After testing, it is not accurate to calculate the offset of Duplicated bones and DHI by using the subtraction between translate.

According to the theory of radial basis functions, after retargeting, when using metahuman's controller to drive the new bones, the distance between the old and the new is also needed, instead of simply calculating the offset .

**Comment by revoconner** [comment]
Think the offset also applies to the translations by controllers, let me know
